apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/Open-ICT-Integrator/discord_bot:latest
          envFrom:
            - secretRef:
              name: discord-bot-secret
