name: CI Test

env:
  PYTHON_VERSION: 3.12.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Run tests with coverage and pytest
        run: |
          coverage run -m pytest ./tests
          coverage xml
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3